-- =====================================================================================
-- ARCHIVO: Actualizacion_Identity.sql
-- PROPÓSITO: REFERENCIA HISTÓRICA — NO EJECUTAR
--
-- Este script fue generado durante el desarrollo inicial cuando se migró
-- una base de datos antigua al esquema de ASP.NET Core Identity.
--
-- Para el entorno actual, este script ya NO aplica.
-- La base de datos se crea completamente desde cero ejecutando:
--
--    Base_de_datos.sql  →  Crea todas las tablas con Identity integrado
--    SPs_1-4.sql        →  Crea los 5 Procedimientos Almacenados
--
-- Alternativamente, desde Visual Studio con el proyecto FondoXYZ.Infrastructure:
--    Update-Database   →  Aplica migraciones de Entity Framework Core
--
-- =====================================================================================
PRINT 'Este script es de referencia histórica. Ejecute Base_de_datos.sql en su lugar.';
